// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace VueApp.Server.Data
{
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
        {
        }

        public DatabaseContext(DbContextOptions<DatabaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MonthlyRevenue> MonthlyRevenues { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=Database;Integrated Security=true");

            modelBuilder.Entity<MonthlyRevenue>(entity =>
            {
                entity.HasKey(e => e.CompanyCode);

                entity.ToTable("MonthlyRevenue");

                entity.HasIndex(e => e.CompanyCode, "idx_CompanyCode");

                entity.Property(e => e.CompanyCode).ValueGeneratedNever();

                entity.Property(e => e.CompanyName).HasMaxLength(8);

                entity.Property(e => e.CumulativeComparisonPercentage).HasColumnType("numeric(24, 18)");

                entity.Property(e => e.Industry).HasMaxLength(8);

                entity.Property(e => e.MonthComparisonPercentage).HasColumnType("numeric(24, 18)");

                entity.Property(e => e.Notes).HasMaxLength(85);

                entity.Property(e => e.RecordNumber)
                    .ValueGeneratedOnAdd()
                    .HasColumnName("_record_number");

                entity.Property(e => e.YearComparisonPercentage).HasColumnType("numeric(24, 18)");
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}