// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using WebAPIs.Models;

namespace WebAPIs.Models
{
    public partial class MonthlyRevenue
    {
        public int RecordNumber { get; set; }
        public int? ReportDate { get; set; }
        public int? DataYearMonth { get; set; }
        public int CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Industry { get; set; }
        public long? CurrentMonthRevenue { get; set; }
        public long? PreviousMonthRevenue { get; set; }
        public long? LastYearSameMonthRevenue { get; set; }
        public decimal? MonthComparisonPercentage { get; set; }
        public decimal? YearComparisonPercentage { get; set; }
        public long? CumulativeCurrentYearRevenue { get; set; }
        public long? CumulativeLastYearRevenue { get; set; }
        public decimal? CumulativeComparisonPercentage { get; set; }
        public string Notes { get; set; }
    }
}